version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_URL=${DATABASE_URL}

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
